# Generated by Django 4.2.4 on 2023-09-01 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simplelib', '0002_book_loan_loan_unique_book_borrower_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='taken',
            field=models.DateField(auto_now_add=True),
        ),
    ]
